[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Temporarily pinning to v4 until Netlify Forms migration is completed
[[plugins]]
  package = "@netlify/plugin-nextjs@4.41.2"
